version: '3.2'

services:
    nimbus:
        container_name: nimbus
        build: ./storm-nimbus
        command: sleep infinity
        tty: true
        ports:
            - 8998:8998 #debug
            - 6627:6627 #thrift
        volumes:
            - './storm-nimbus:/storm-nimbus'
        environment:
            - STORM_JAR_JVM_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:8998"

    data-reader:
        container_name: data-reader
        build: ./data-reader
        depends_on:
            - redis
        ports:
            - 5678:5678
        tty: true
        volumes:
            - './data-reader:/data-reader'

    redis:
        container_name: redis
        image: redis:latest
        ports:
        - "6379:6379"            

volumes:
    storm-nimbus:
    data-reader: